version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network_backend

  web:
    build: .
    command: >
      bash -c "python mysite/manage.py migrate &&
               python mysite/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=django_db
      - DB_USER=django_user
      - DB_PASSWORD=django_password
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - network_backend
      - network_frontend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - network_frontend
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  network_backend:
    internal: true 
  network_frontend:
